name: Sync Notion Article to GitHub Issue

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  sync_to_github_issue:
    if: ${{ github.event.notion && github.event.notion.properties.Status === "published" }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install @notionhq/client
      - name: Fetch Notion Article
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          node .github/workflows/fetch-notion-article.js
      - name: Create new GitHub Issue
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: ${{ env.NOTION_ARTICLE_TITLE }}
          body: ${{ env.NOTION_ARTICLE_CONTENT }}
          labels: sync-from-notion
        env:
          GITHUB_TOKEN: ${{ secrets.G_T }}
